
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const uid=()=>Math.random().toString(36).slice(2,10);
const todayKey=()=>new Date().toISOString().slice(0,10);
const tomorrowKey=()=>new Date(Date.now()+86400000).toISOString().slice(0,10);
const doneStatus=t=>['已完成','需要复习'].includes(t.status);
const fmtMin=m=>{m=Number(m||0); if(m<60)return m+' 分钟'; return Math.floor(m/60)+' 小时 '+(m%60?m%60+' 分钟':'')};
const defaultState=()=>({
  version:'v3',theme:'space',page:'home',
  weekTasks:[],dailyTasks:[],sessions:[],distractions:[],review:'',reviewSuggestions:[],focusTaskId:null,timerSeconds:45*60,elapsedSeconds:0,timerRunning:false,energy:0,streak:0,lastActiveDate:'',
  settings:{focusMinutes:45,restMinutes:10,longRestMinutes:20,longRestEvery:4,apiParseUrl:'',apiReviewUrl:''}
});
const demoState=()=>({
  ...defaultState(),
  weekTasks:[{id:uid(),subject:'C/C++',content:'指针、文件操作、结构体、链表',estimate:720,actual:120,priority:'高',deadline:'周日 22:00',note:'指针和链表重点复习',status:'进行中'}],
  dailyTasks:[
    {id:uid(),date:todayKey(),subject:'C/C++',content:'复习返回指针',estimate:45,actual:0,planTime:'20:30 前',type:'知识理解',difficulty:'中等',status:'未开始',mastery:'',note:'',focusMinutes:45,restMinutes:10},
    {id:uid(),date:todayKey(),subject:'线性代数',content:'做线性空间例题',estimate:60,actual:0,planTime:'',type:'做题',difficulty:'中等',status:'未开始',mastery:'',note:'',focusMinutes:60,restMinutes:10},
    {id:uid(),date:todayKey(),subject:'德语',content:'背单词',estimate:30,actual:0,planTime:'',type:'背诵',difficulty:'简单',status:'未开始',mastery:'',note:'',focusMinutes:30,restMinutes:5}
  ]
});
let state; try{state=JSON.parse(localStorage.getItem('focusmap_v3')||'null')||defaultState()}catch(e){state=defaultState()}
if(!state.settings) state.settings=defaultState().settings;
function save(){localStorage.setItem('focusmap_v3',JSON.stringify(state));}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function go(page){state.page=page;save();$$('.page').forEach(p=>p.classList.toggle('active',p.id===page));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const titles={home:['首页','先看今天地图，再进入一个节点。'],week:['周任务','规划本周方向，必要时拆到今天。'],daily:['每日任务','手动添加，或者输入一段话智能识别。'],map:['今日图谱','发散式地图，点击节点开始专注。'],focus:['专注','这一页会随时间变化。'],break:['休息','抽一个恢复动作，不要刷短视频。'],review:['复盘','用数据分析今天，不靠自责。'],settings:['设置','自定义时间和 API 接入。']};$('#pageTitle').textContent=titles[page][0];$('#pageSub').textContent=titles[page][1];render();}
function setTheme(theme){state.theme=theme;document.body.dataset.theme=theme;save();$$('[data-theme-btn]').forEach(b=>b.classList.toggle('active',b.dataset.themeBtn===theme));makeDecor();renderArt();renderFocusThemeLabel();}
function makeDecor(){const d=$('#decor');d.innerHTML='';const theme=state.theme;if(theme==='space'){for(let i=0;i<70;i++){let s=document.createElement('span');s.className='star';s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.animationDelay=Math.random()*4+'s';d.appendChild(s)}for(let i=0;i<3;i++){let o=document.createElement('span');o.className='orbit';o.style.left=(8+i*30)+'%';o.style.top=(12+i*20)+'%';o.style.animationDelay=(-i*4)+'s';d.appendChild(o)}let m=document.createElement('span');m.className='meteor';d.appendChild(m)}
if(theme==='wuxia'){for(let i=0;i<5;i++){let ink=document.createElement('span');ink.className='ink';ink.style.left=(5+i*20)+'%';ink.style.top=(10+i*14)+'%';ink.style.animationDelay=(-i*2)+'s';d.appendChild(ink)}for(let i=0;i<18;i++){let l=document.createElement('span');l.className='leaf';l.textContent='🍂';l.style.left=Math.random()*100+'%';l.style.animationDelay=Math.random()*10+'s';d.appendChild(l)}}
if(theme==='dragon'){for(let i=0;i<5;i++){let c=document.createElement('span');c.className='cloud';c.style.top=(8+i*16)+'%';c.style.animationDelay=(-i*3)+'s';d.appendChild(c)}for(let i=0;i<22;i++){let b=document.createElement('span');b.className=i%4?'bubble':'heart';b.textContent=i%4?'':'💗';b.style.left=Math.random()*100+'%';b.style.top=Math.random()*100+'%';b.style.animationDelay=Math.random()*8+'s';d.appendChild(b)}}}
const svg={
space:`<svg viewBox="0 0 360 280" class="floaty"><defs><linearGradient id="s1" x1="0" x2="1"><stop stop-color="#70e1ff"/><stop offset="1" stop-color="#a989ff"/></linearGradient></defs><circle cx="178" cy="139" r="94" fill="rgba(112,225,255,.12)" stroke="rgba(112,225,255,.35)"/><ellipse cx="178" cy="145" rx="142" ry="36" fill="none" stroke="rgba(255,255,255,.24)"/><path d="M177 61 C210 96 213 179 177 219 C143 181 141 96 177 61Z" fill="url(#s1)"/><circle cx="177" cy="132" r="22" fill="#06122d" stroke="#fff"/><path d="M154 196 L130 235 L170 215Z" fill="#70e1ff"/><path d="M200 196 L224 235 L184 215Z" fill="#a989ff"/><circle cx="54" cy="56" r="6" fill="#fff"/><circle cx="302" cy="78" r="8" fill="#ffda7b"/><circle cx="284" cy="210" r="4" fill="#fff"/></svg>`,
wuxia:`<svg viewBox="0 0 360 280" class="floaty"><path d="M25 214 C80 148 116 174 166 112 C213 53 270 70 335 38 L335 248 L25 248Z" fill="rgba(35,100,87,.18)"/><path d="M42 225 C95 173 130 193 178 140 C226 88 278 98 326 74" fill="none" stroke="#236457" stroke-width="4" opacity=".55"/><circle cx="255" cy="74" r="34" fill="rgba(164,92,42,.18)"/><path d="M162 48 C179 90 177 160 159 226" stroke="#2a2118" stroke-width="5" fill="none"/><path d="M118 90 C161 91 210 83 252 62" stroke="#a45c2a" stroke-width="5" fill="none"/><path d="M142 111 L91 211" stroke="#2a2118" stroke-width="3"/><path d="M188 99 L262 207" stroke="#2a2118" stroke-width="3"/><text x="52" y="74" font-size="30" fill="#a45c2a" font-family="serif">修炼</text></svg>`,
dragon:`<svg viewBox="0 0 360 280" class="floaty"><ellipse cx="180" cy="226" rx="116" ry="22" fill="rgba(255,132,189,.22)"/><path d="M112 142 C93 98 126 67 166 77 C181 45 233 52 241 92 C279 99 291 139 268 168 C251 194 203 193 170 185 C142 199 121 181 112 142Z" fill="#fff" stroke="#ff84bd" stroke-width="5"/><circle cx="153" cy="125" r="8" fill="#483148"/><circle cx="222" cy="125" r="8" fill="#483148"/><path d="M171 151 Q188 163 205 151" stroke="#483148" stroke-width="5" fill="none" stroke-linecap="round"/><path d="M132 83 L112 48 L153 68" fill="#ffbc58" stroke="#ff84bd" stroke-width="4"/><path d="M226 72 L264 45 L246 90" fill="#8ac7ff" stroke="#ff84bd" stroke-width="4"/><circle cx="116" cy="132" r="10" fill="#ffb3d3"/><circle cx="245" cy="132" r="10" fill="#ffb3d3"/><path d="M250 171 Q300 177 297 128" stroke="#ff84bd" stroke-width="15" fill="none" stroke-linecap="round"/><text x="126" y="235" font-size="22" fill="#ff84bd" font-weight="900">加油呀</text></svg>`
};
function renderArt(){const art=svg[state.theme]||svg.space;$('#heroArt').innerHTML=art;$('#focusArt').innerHTML=art;}
function todayTasks(){return state.dailyTasks.filter(t=>t.date===todayKey())}
function renderStats(){const tasks=todayTasks();const done=tasks.filter(doneStatus).length;const actual=tasks.reduce((s,t)=>s+Number(t.actual||0),0);const planned=tasks.reduce((s,t)=>s+Number(t.estimate||0),0);const dis=state.distractions.filter(d=>d.date===todayKey()).length;$('#stats').innerHTML=`<div class="stat"><strong>${done}/${tasks.length}</strong><span>今日节点</span></div><div class="stat"><strong>${fmtMin(actual)}</strong><span>实际专注</span></div><div class="stat"><strong>${fmtMin(planned)}</strong><span>预计任务</span></div><div class="stat"><strong>${state.energy}</strong><span>${energyName()}</span></div>`;$('#quickStatus').textContent=tasks.length?`今日 ${tasks.length} 个节点，已完成 ${done} 个，分心记录 ${dis} 次。`:'今日还没有任务。可以用智能导入快速生成。'}
function energyName(){return state.theme==='space'?'星能':state.theme==='wuxia'?'修为':'奶龙能量'}
function taskBadges(t){return `<span class="badge">${t.subject}</span><span class="badge">预计 ${fmtMin(t.estimate)}</span><span class="badge">实际 ${fmtMin(t.actual||0)}</span><span class="badge">${t.status}</span>${t.mastery?`<span class="badge">${t.mastery}</span>`:''}`}
function renderWeek(){const box=$('#weekList');if(!state.weekTasks.length){box.innerHTML='<div class="empty">还没有周任务。先添加一个本周目标，再拆到今天。</div>';return}box.innerHTML=state.weekTasks.map(w=>{const related=state.dailyTasks.filter(t=>t.weekId===w.id);const done=related.filter(doneStatus).length;const pct=related.length?Math.round(done/related.length*100):0;return `<div class="task-card"><div><h4>${w.subject}｜${w.content}</h4><p>${taskBadges({subject:w.priority,estimate:w.estimate,actual:w.actual,status:w.status})}</p><p class="mini">截止：${w.deadline||'未设置'} ${w.note?'｜'+w.note:''}</p><div class="progress"><i style="width:${pct}%"></i></div></div><div class="row"><button class="small splitWeek" data-id="${w.id}">拆到今天</button><button class="small deleteWeek" data-id="${w.id}">删除</button></div></div>`}).join('')}
function renderDaily(){const box=$('#dailyList');const tasks=todayTasks();if(!tasks.length){box.innerHTML='<div class="empty">今日任务为空。你可以手动添加，也可以输入一段话智能导入。</div>';return}box.innerHTML=tasks.map(t=>`<div class="task-card"><div><h4>${doneStatus(t)?'✓ ':''}${t.subject}｜${t.content}</h4><p>${taskBadges(t)}</p><p class="mini">类型：${t.type||'未设'}｜难度：${t.difficulty||'未设'}｜${t.planTime||'未设置完成时间'}</p></div><div class="row"><button class="small startTask" data-id="${t.id}">开始</button><button class="small quickDone" data-id="${t.id}">划掉</button><button class="small reviewTask" data-id="${t.id}">需复习</button><button class="small deleteDaily" data-id="${t.id}">删除</button></div></div>`).join('')}
function renderRadial(container, compact=false){const el=$(container);const tasks=todayTasks();if(!tasks.length){el.innerHTML='<div class="empty">今日图谱为空。先去“每日任务”输入一段话，让系统自动识别节点。</div>';return}const w=compact?620:820,h=compact?470:600,cx=w/2,cy=h/2;const radius=compact?170:220;const lines=tasks.map((t,i)=>{const a=(360/tasks.length*i-90)*Math.PI/180;const x=cx+Math.cos(a)*radius,y=cy+Math.sin(a)*radius;return `<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" class="${doneStatus(t)?'done-line':''}"/>`}).join('');const nodes=tasks.map((t,i)=>{const angle=360/tasks.length*i-90;return `<div class="radial-node ${doneStatus(t)?'done':''} ${t.status==='需要复习'?'review':''} ${state.focusTaskId===t.id?'activeTask':''}" style="--angle:${angle}deg;--radius:${radius}px"><div class="node-title">${doneStatus(t)?'✓ ':''}${themeNodeName(t)}</div><div class="mini">${t.content}</div><div>${taskBadges(t)}</div><div class="node-actions"><button class="small startTask" data-id="${t.id}">开始</button><button class="small quickDone" data-id="${t.id}">划掉</button></div></div>`}).join('');el.innerHTML=`<div class="radial-graph" style="width:${w}px;height:${h}px"><svg class="graph-lines" viewBox="0 0 ${w} ${h}">${lines}</svg><div class="graph-center">今日目标<small>${tasks.filter(doneStatus).length}/${tasks.length} 已点亮</small></div>${nodes}</div>`}
function themeNodeName(t){if(state.theme==='space')return `${t.subject}星球`;if(state.theme==='wuxia')return `${t.subject}招式`;return `${t.subject}糖果`}
function renderMap(){renderRadial('#mapGraph',false);renderRadial('#homeMap',true)}
function renderFunPanel(){const tasks=todayTasks();const done=tasks.filter(doneStatus).length;const message=state.theme==='space'?`今日航线已点亮 ${done} 个星球。`:state.theme==='wuxia'?`今日修炼已完成 ${done} 式。`:`今天小奶龙收集了 ${done} 颗能量糖。`;$('#funPanel').innerHTML=`<div class="task-card"><div><h4>${energyName()}：${state.energy}</h4><p>${message}</p></div></div><div class="task-card"><div><h4>连续感</h4><p>每完成一个节点，就会获得能量。完成所有节点会触发庆祝动画。</p></div></div><div class="task-card"><div><h4>下一步建议</h4><p>${tasks.find(t=>!doneStatus(t))?`先做 “${tasks.find(t=>!doneStatus(t)).content}”。`:'今天的任务已经点亮完啦。'}</p></div></div>`}
function renderReviewStats(){const tasks=todayTasks();const done=tasks.filter(doneStatus).length;const planned=tasks.reduce((s,t)=>s+Number(t.estimate||0),0);const actual=tasks.reduce((s,t)=>s+Number(t.actual||0),0);const over=tasks.filter(t=>Number(t.actual||0)>Number(t.estimate||0)).length;const dis=state.distractions.filter(d=>d.date===todayKey()).length;$('#reviewStats').innerHTML=`<div class="task-card"><div><h4>完成任务</h4><p>${done} / ${tasks.length}</p></div></div><div class="task-card"><div><h4>预计与实际</h4><p>预计 ${fmtMin(planned)}，实际 ${fmtMin(actual)}</p></div></div><div class="task-card"><div><h4>超时任务</h4><p>${over} 个</p></div></div><div class="task-card"><div><h4>分心记录</h4><p>${dis} 次</p></div></div>`; if(state.review)$('#reviewBox').textContent=state.review}
function renderFocus(){const t=state.dailyTasks.find(x=>x.id===state.focusTaskId);if(t){$('#focusTaskTitle').textContent=`${t.subject}｜${t.content}`;$('#focusTaskDesc').textContent=`预计 ${fmtMin(t.estimate)}，本轮专注 ${fmtMin(t.focusMinutes||state.settings.focusMinutes)}，休息 ${fmtMin(t.restMinutes||state.settings.restMinutes)}`;$('#focusMinutesNow').value=t.focusMinutes||state.settings.focusMinutes;$('#restMinutesNow').value=t.restMinutes||state.settings.restMinutes}else{$('#focusTaskTitle').textContent='还没有选择任务';$('#focusTaskDesc').textContent='去今日图谱点一个节点，就能进入专注。';$('#focusMinutesNow').value=state.settings.focusMinutes;$('#restMinutesNow').value=state.settings.restMinutes}const tasks=todayTasks().filter(t=>!doneStatus(t));$('#focusTaskPicker').innerHTML=tasks.length?tasks.map(t=>`<div class="task-card"><div><h4>${t.subject}</h4><p>${t.content}</p></div><button class="small startTask" data-id="${t.id}">选择</button></div>`).join(''):'<div class="empty">今日任务都完成了，可以去复盘。</div>';updateTimerText();updateStage();renderFocusThemeLabel();}
function renderFocusThemeLabel(){const labels={space:['回到航线','飞船偏航了也没关系，调回方向就行。'],wuxia:['重新入定','心乱一下很正常，重新收势。'],dragon:['小奶龙拉我回来','摸摸小奶龙，继续这个节点。']};const l=labels[state.theme]||labels.space;$('#themeActionLabel').innerHTML=`<strong>${l[0]}</strong><span>${l[1]}</span>`}
function renderSettings(){const s=state.settings;$('#setFocus').value=s.focusMinutes;$('#setRest').value=s.restMinutes;$('#setLongRest').value=s.longRestMinutes;$('#setLongEvery').value=s.longRestEvery;$('#apiParseUrl').value=s.apiParseUrl||'';$('#apiReviewUrl').value=s.apiReviewUrl||''}
function render(){renderArt();renderStats();renderWeek();renderDaily();renderMap();renderFunPanel();renderFocus();renderReviewStats();renderSettings()}
function localParse(text){const raw=text.replace(/；/g,';').replace(/。/g,';').replace(/\n/g,';').split(/[;；]/).map(x=>x.trim()).filter(Boolean);const tasks=[];const subjectKeywords={
'C/C++':['c++','cpp','C++','指针','链表','结构体','fread','fwrite','文件','函数','数组'],
'线性代数':['线代','线性代数','矩阵','行列式','特征值','特征向量','线性空间','线性变换','基','维数'],
'大学物理':['物理','电磁','高斯','安培','麦克斯韦','磁场','电场','波动','热学','刚体'],
'高等数学':['高数','积分','偏导','微分','曲线积分','曲面积分','泰勒','极限'],
'德语':['德语','单词','语法','听力','口语','阅读','德福'],
'总结':['总结','复盘','整理']};
function subjectOf(s){for(const [sub,ks] of Object.entries(subjectKeywords)){if(ks.some(k=>s.toLowerCase().includes(k.toLowerCase())))return sub}return '其他'}
function minutesOf(s){let n=45;let m=s.match(/(\d+(?:\.\d+)?)\s*个?半?小时/);if(m)n=Math.round(Number(m[1])*60);if(/一个半小时|1个半小时|1\.5小时/.test(s))n=90;if(/半小时/.test(s)&&!m)n=30;let mm=s.match(/(\d+)\s*分钟/);if(mm)n=Number(mm[1]);let h=s.match(/(\d+)\s*小时/);if(h&&!/半小时/.test(s))n=Number(h[1])*60;return n}
function typeOf(s){if(/题|练习|刷题/.test(s))return '做题';if(/背|单词|记忆/.test(s))return '背诵';if(/总结|整理|复盘/.test(s))return '复盘';return '知识理解'}
const chunks=raw.length?raw:text.split(/[，,]/).map(x=>x.trim()).filter(Boolean);
chunks.forEach(c=>{let sub=subjectOf(c);let min=minutesOf(c);let content=c.replace(/大概|预计|左右|今天|晚上|上午|下午/g,'').replace(/\d+(?:\.\d+)?\s*小时|\d+\s*分钟|一个半小时|半小时/g,'').trim();if(!content)content=c;tasks.push({id:uid(),date:todayKey(),subject:sub,content,estimate:min,actual:0,planTime:'',type:typeOf(c),difficulty:min>=60?'中等':'简单',status:'未开始',mastery:'',note:'',focusMinutes:min,restMinutes:state.settings.restMinutes})});return tasks}
async function parseNatural(){const text=$('#naturalInput').value.trim();if(!text){toast('先输入一段今天想学什么');return}let tasks=[];const url=state.settings.apiParseUrl;if(url){try{const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});const data=await res.json();tasks=(data.tasks||data.result?.tasks||[]).map(x=>({id:uid(),date:todayKey(),subject:x.subject||'其他',content:x.content||x.title||'',estimate:Number(x.estimatedMinutes||x.estimate||45),actual:0,planTime:x.planTime||'',type:x.taskType||x.type||'知识理解',difficulty:x.difficulty||'中等',status:'未开始',mastery:'',note:'API识别',focusMinutes:Number(x.focusMinutes||x.estimatedMinutes||45),restMinutes:state.settings.restMinutes}));toast('已通过 API 识别任务')}catch(e){toast('API 调用失败，已切换为本地识别');tasks=localParse(text)}}else tasks=localParse(text);state.previewTasks=tasks;renderPreview(tasks)}
function renderPreview(tasks){const box=$('#parsePreview');if(!tasks.length){box.innerHTML='<div class="empty">没有识别到任务，可以换一种写法。</div>';return}box.innerHTML='<h3 style="margin-top:16px">识别结果</h3>'+tasks.map((t,i)=>`<div class="preview-row"><div><strong>${t.subject}｜${t.content}</strong><p class="mini">预计 ${fmtMin(t.estimate)}｜${t.type}｜${t.difficulty}</p></div><button class="small removePreview" data-i="${i}">移除</button></div>`).join('')+'<button class="primary" id="addPreviewTasks">加入今日图谱</button>'}
function addPreview(){const tasks=state.previewTasks||[];state.dailyTasks.push(...tasks);state.previewTasks=[];save();render();$('#parsePreview').innerHTML='';toast('已加入今日图谱');go('map')}
function selectTask(id){state.focusTaskId=id;const t=state.dailyTasks.find(x=>x.id===id);if(t){t.status='进行中';state.timerSeconds=Number(t.focusMinutes||t.estimate||state.settings.focusMinutes)*60;state.elapsedSeconds=0;save();go('focus');toast('已进入专注节点')}}
let timer=null,breakTimer=null,breakLeft=10*60,lastStage='start';
function getProgress(){const t=state.dailyTasks.find(x=>x.id===state.focusTaskId);const total=(t?Number(t.focusMinutes||t.estimate||state.settings.focusMinutes):state.settings.focusMinutes)*60;return Math.min(1,state.elapsedSeconds/Math.max(1,total))}
function getStage(p){if(p>=1)return'done';if(p>=.75)return'final';if(p>=.5)return'deep';if(p>=.25)return'warm';return'start'}
const stageMessages={space:{start:['飞船离港','先稳定航线，只做这个节点。'],warm:['穿过第一片星云','最难的启动已经过去了。'],deep:['深空巡航','现在进入中段，不要切出去。'],final:['目标星球在前方','快点亮这个任务星球了。'],done:['星球已点亮','这一轮完成，可以休息一下。']},wuxia:{start:['静气凝神','先练这一招，不必管别的。'],warm:['一炷香已过','招式渐稳，继续保持。'],deep:['此刻入定','心神收住，别换任务。'],final:['快收势了','再坚持片刻，这一式要成了。'],done:['今日一式已成','可以收剑休息。']},dragon:{start:['小奶龙坐好啦','它陪你开始这一轮。'],warm:['吃到第一颗能量豆','学习能量开始上涨。'],deep:['能量正在变满','继续这个节点，不要跑走。'],final:['小奶龙举起小旗','马上就点亮啦。'],done:['好耶完成啦','小奶龙帮你划掉这个节点。']}};
function updateStage(){const p=getProgress();const st=getStage(p);const fc=$('#focusCard');fc.classList.remove('stage-start','stage-warm','stage-deep','stage-final','stage-done');fc.classList.add('stage-'+st);const msg=(stageMessages[state.theme]||stageMessages.space)[st];$('#stageBox').innerHTML=`<strong>${msg[0]}</strong><span>${msg[1]}</span>`;if(st!==lastStage&&['warm','deep','final','done'].includes(st)){toast(msg[0]+'：'+msg[1]);lastStage=st}}
function updateTimerText(){const s=Math.max(0,state.timerSeconds);const m=String(Math.floor(s/60)).padStart(2,'0'),sec=String(s%60).padStart(2,'0');$('#timerText').textContent=`${m}:${sec}`;$('#timerRing').style.setProperty('--ring',Math.round(getProgress()*100)+'%');}
function startTimer(){if(timer)return;state.timerRunning=true;timer=setInterval(()=>{state.timerSeconds=Math.max(0,state.timerSeconds-1);state.elapsedSeconds++;if(state.timerSeconds===0){stopTimer();updateStage();toast('这一轮时间到了，可以完成或加时');}updateTimerText();updateStage();save()},1000);$('#startPause').textContent='暂停'}
function stopTimer(){if(timer){clearInterval(timer);timer=null}state.timerRunning=false;$('#startPause').textContent='开始';save()}
function resetTimer(){stopTimer();const t=state.dailyTasks.find(x=>x.id===state.focusTaskId);state.timerSeconds=(t?Number(t.focusMinutes||t.estimate||state.settings.focusMinutes):state.settings.focusMinutes)*60;state.elapsedSeconds=0;lastStage='start';save();renderFocus()}
function openFinish(){const t=state.dailyTasks.find(x=>x.id===state.focusTaskId);if(!t){toast('请先选择一个任务');return}stopTimer();$('#finishSummary').textContent=`任务：${t.subject}｜${t.content}。本轮累计 ${Math.floor(state.elapsedSeconds/60)} 分 ${state.elapsedSeconds%60} 秒。`;$('#taskNote').value=t.note||'';$('#finishModal').classList.add('show')}
function finishTask(status='已完成'){const t=state.dailyTasks.find(x=>x.id===state.focusTaskId);if(!t)return;const mins=Math.max(1,Math.round(state.elapsedSeconds/60)||Number(t.focusMinutes||t.estimate||1));t.actual=Number(t.actual||0)+mins;t.status=status;t.mastery=$('#masterySelect').value;t.note=$('#taskNote').value.trim();state.sessions.push({id:uid(),taskId:t.id,date:todayKey(),duration:mins,subject:t.subject,content:t.content,status,mastery:t.mastery});state.energy+=Math.max(3,Math.round((t.estimate||mins)/5));state.focusTaskId=null;state.elapsedSeconds=0;state.timerSeconds=state.settings.focusMinutes*60;save();$('#finishModal').classList.remove('show');celebrate(doneStatus(t));toast(status==='需要复习'?'已保存为需要复习':'节点已划掉');go('map')}
function quickSet(id,status){const t=state.dailyTasks.find(x=>x.id===id);if(!t)return;t.status=status;t.mastery=status==='需要复习'?'有点懂':'只是完成了';t.actual=t.actual||Number(t.estimate||1);state.energy+=Math.max(2,Math.round((t.estimate||10)/8));save();render();toast(status==='需要复习'?'已标记为需要复习':'已划掉节点')}
function celebrate(){const c=$('#confetti');c.innerHTML='';for(let i=0;i<56;i++){let p=document.createElement('i');p.style.left=Math.random()*100+'%';p.style.background=i%3===0?'var(--accent)':i%3===1?'var(--accent2)':'var(--warn)';p.style.animationDelay=Math.random()*0.35+'s';c.appendChild(p)}setTimeout(()=>c.innerHTML='',1800)}
function addDistraction(reason){if(!state.focusTaskId){toast('先选择任务再记录分心');return}state.distractions.push({id:uid(),date:todayKey(),taskId:state.focusTaskId,reason,time:new Date().toLocaleTimeString()});save();toast('已记录：'+reason)}
function splitWeekToToday(id){const w=state.weekTasks.find(x=>x.id===id);if(!w)return;const parts=w.content.split(/[、，,]/).map(x=>x.trim()).filter(Boolean).slice(0,6);const add=parts.length?parts:[w.content];add.forEach((p,i)=>state.dailyTasks.push({id:uid(),date:todayKey(),subject:w.subject,content:p,estimate:i===0?45:40,actual:0,planTime:'',type:'知识理解',difficulty:'中等',status:'未开始',mastery:'',note:'来自周任务：'+w.content,weekId:w.id,focusMinutes:i===0?45:40,restMinutes:state.settings.restMinutes}));save();render();toast('已拆成今日发散图谱节点')}
function drawBreakTip(){const tips=['喝水，并离开座位 1 分钟','看窗外 30 秒，让眼睛恢复一下','做 6 次肩颈环绕','慢慢呼吸 5 次，不看手机','站起来走 100 步','闭眼休息 60 秒','把桌面上最碍眼的东西收一下'];const tip=tips[Math.floor(Math.random()*tips.length)];$('#breakTip').textContent=tip;$('#breakTipTitle').textContent=state.theme==='space'?'补给舱建议':state.theme==='wuxia'?'调息建议':'奶龙休息盲盒'}
function generateLocalReview(){const tasks=todayTasks();if(!tasks.length){$('#reviewBox').textContent='今天还没有任务数据，先添加几个任务并完成一轮专注。';return}const done=tasks.filter(doneStatus),planned=tasks.reduce((s,t)=>s+Number(t.estimate||0),0),actual=tasks.reduce((s,t)=>s+Number(t.actual||0),0),overtime=tasks.filter(t=>Number(t.actual||0)>Number(t.estimate||0)),undone=tasks.filter(t=>!doneStatus(t)),reviewNeed=tasks.filter(t=>t.status==='需要复习'||t.mastery==='有点懂'||t.mastery==='还不会'),dis=state.distractions.filter(d=>d.date===todayKey());const byReason={};dis.forEach(d=>byReason[d.reason]=(byReason[d.reason]||0)+1);const topReason=Object.entries(byReason).sort((a,b)=>b[1]-a[1])[0];const subjectActual={};tasks.forEach(t=>subjectActual[t.subject]=(subjectActual[t.subject]||0)+Number(t.actual||0));const topSubject=Object.entries(subjectActual).sort((a,b)=>b[1]-a[1])[0];let lines=[];lines.push(`今日概况\n你今天完成了 ${done.length} 个任务中的 ${tasks.length} 个。预计学习 ${fmtMin(planned)}，实际记录 ${fmtMin(actual)}。${topSubject?`主要投入在 ${topSubject[0]}。`:''}`);lines.push(overtime.length?`\n时间偏差\n${overtime.map(t=>`“${t.content}”预计 ${fmtMin(t.estimate)}，实际 ${fmtMin(t.actual)}`).join('；')}。这说明这些内容比预想更费时间，下次可以多预留 20 到 30 分钟。`:`\n时间偏差\n今天暂时没有明显超时任务。如果实际记录偏少，可以在专注结束时尽量保存真实用时。`);lines.push(reviewNeed.length?`\n学习质量\n${reviewNeed.map(t=>`“${t.content}”`).slice(0,3).join('、')} 还不适合完全划过。建议明天安排短复盘。`:`\n学习质量\n今天完成的节点掌握程度比较稳定，可以继续推进。`);lines.push(topReason?`\n状态分析\n你今天记录了 ${dis.length} 次分心，最常见原因是“${topReason[0]}”。这不是单纯自制力问题，更可能说明任务颗粒度或学习状态需要调整。`:`\n状态分析\n今天没有记录分心原因。之后如果卡住，可以点一下分心按钮，这会让复盘更准确。`);let suggestions=[];reviewNeed.slice(0,2).forEach(t=>suggestions.push({subject:t.subject,content:`复盘 ${t.content}`,estimate:20}));undone.slice(0,2).forEach(t=>suggestions.push({subject:t.subject,content:`继续 ${t.content}`,estimate:t.estimate}));if(!suggestions.length)suggestions=[{subject:'复盘',content:'整理今天错题或笔记',estimate:30},{subject:'新任务',content:'选择一个新知识点',estimate:45}];state.reviewSuggestions=suggestions;lines.push(`\n明日建议\n${suggestions.slice(0,3).map((s,i)=>`${i+1}. ${s.subject}｜${s.content}，${fmtMin(s.estimate)}`).join('\n')}\n建议明天先安排 3 个核心节点，不要一开始就把全天塞满。`);state.review=lines.join('\n');save();renderReviewStats();toast('今日总结已生成')}
async function generateReview(){const url=state.settings.apiReviewUrl;if(!url){generateLocalReview();return}try{const payload={date:todayKey(),tasks:todayTasks(),sessions:state.sessions.filter(s=>s.date===todayKey()),distractions:state.distractions.filter(d=>d.date===todayKey())};const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();state.review=data.summary||data.text||JSON.stringify(data,null,2);state.reviewSuggestions=data.tomorrowSuggestions||[];save();renderReviewStats();toast('已通过 API 生成复盘')}catch(e){toast('API 总结失败，已使用本地分析');generateLocalReview()}}
function addTomorrowSuggestions(){const list=state.reviewSuggestions||[];if(!list.length){toast('还没有可加入的明日建议');return}list.forEach(s=>state.dailyTasks.push({id:uid(),date:tomorrowKey(),subject:s.subject||'复盘',content:s.content||s.title||'',estimate:Number(s.estimatedMinutes||s.estimate||30),actual:0,planTime:'',type:'复盘',difficulty:'中等',status:'未开始',mastery:'',note:'来自今日复盘建议',focusMinutes:Number(s.estimatedMinutes||s.estimate||30),restMinutes:state.settings.restMinutes}));save();toast('已加入明日任务')}
function apiGuideText(){return `Vercel 后端接口示例：

export default async function handler(req, res) {
  const { text } = req.body;
  const response = await fetch('https://api.openai.com/v1/responses', {
    method: 'POST',
    headers: {
      'Authorization': 'Bearer ' + process.env.OPENAI_API_KEY,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      model: 'gpt-5.4-mini',
      input: '把下面学习计划拆成 JSON 数组，只输出 tasks 字段：' + text
    })
  });
  const data = await response.json();
  res.status(200).json(JSON.parse(data.output_text));
}

注意：API Key 只能放在 Vercel 环境变量 OPENAI_API_KEY 里，不能写进前端 index.html。`}
function wire(){document.body.dataset.theme=state.theme;makeDecor();renderArt();go(state.page||'home');$$('[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-theme-btn]').forEach(b=>b.onclick=()=>setTheme(b.dataset.themeBtn));
$('#weekForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.weekTasks.push({id:uid(),subject:f.get('subject'),content:f.get('content'),estimate:Number(f.get('estimate')),actual:0,priority:f.get('priority'),deadline:f.get('deadline'),note:f.get('note'),status:'进行中'});e.target.reset();save();render();toast('已添加周任务')};
$('#dailyForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.dailyTasks.push({id:uid(),date:todayKey(),subject:f.get('subject'),content:f.get('content'),estimate:Number(f.get('estimate')),actual:0,planTime:f.get('planTime'),type:f.get('type'),difficulty:f.get('difficulty'),status:'未开始',mastery:'',note:'',focusMinutes:Number(f.get('focusMinutes')||f.get('estimate')||state.settings.focusMinutes),restMinutes:Number(f.get('restMinutes')||state.settings.restMinutes)});e.target.reset();save();render();toast('已加入今日图谱')};
document.addEventListener('click',e=>{const st=e.target.closest('.startTask');if(st)selectTask(st.dataset.id);const q=e.target.closest('.quickDone');if(q)quickSet(q.dataset.id,'已完成');const rv=e.target.closest('.reviewTask');if(rv)quickSet(rv.dataset.id,'需要复习');const dw=e.target.closest('.deleteWeek');if(dw){state.weekTasks=state.weekTasks.filter(t=>t.id!==dw.dataset.id);save();render()}const dd=e.target.closest('.deleteDaily');if(dd){state.dailyTasks=state.dailyTasks.filter(t=>t.id!==dd.dataset.id);save();render()}const sp=e.target.closest('.splitWeek');if(sp)splitWeekToToday(sp.dataset.id);const rm=e.target.closest('.removePreview');if(rm){state.previewTasks.splice(Number(rm.dataset.i),1);renderPreview(state.previewTasks)}if(e.target.id==='addPreviewTasks')addPreview();});
$('#parseNatural').onclick=parseNatural;$('#fillExample').onclick=()=>{$('#naturalInput').value='今天复习C++指针和fread fwrite一个半小时；线代第六章线性空间一小时；德语背单词半小时；最后做今日总结10分钟。'};$('#autoSplit').onclick=()=>state.weekTasks.slice(0,2).forEach(w=>splitWeekToToday(w.id));$('#postponeUndone').onclick=()=>{todayTasks().filter(t=>!doneStatus(t)).forEach(t=>{t.date=tomorrowKey();t.status='延期'});save();render();toast('未完成任务已转到明天')};$('#clearToday').onclick=()=>{if(confirm('清空今天所有任务吗？')){state.dailyTasks=state.dailyTasks.filter(t=>t.date!==todayKey());save();render();toast('今日任务已清空')}};
$('#startPause').onclick=()=>timer?stopTimer():startTimer();$('#addTen').onclick=()=>{state.timerSeconds+=600;save();updateTimerText();toast('已加 10 分钟')};$('#resetTimer').onclick=resetTimer;$('#finishFocus').onclick=openFinish;$$('.distraction').forEach(b=>b.onclick=()=>addDistraction(b.dataset.reason));$('#applyFocusNow').onclick=()=>{const t=state.dailyTasks.find(x=>x.id===state.focusTaskId);if(t){t.focusMinutes=Number($('#focusMinutesNow').value||state.settings.focusMinutes);t.restMinutes=Number($('#restMinutesNow').value||state.settings.restMinutes);state.timerSeconds=t.focusMinutes*60;state.elapsedSeconds=0;save();renderFocus();toast('已应用到本轮')}};$('#confirmFinish').onclick=()=>finishTask('已完成');$('#needReview').onclick=()=>finishTask('需要复习');$('#closeModal').onclick=()=>$('#finishModal').classList.remove('show');
$('#breakStart').onclick=()=>{drawBreakTip();if(breakTimer){clearInterval(breakTimer);breakTimer=null;$('#breakStart').textContent='继续休息';return}$('#breakStart').textContent='暂停';breakTimer=setInterval(()=>{breakLeft=Math.max(0,breakLeft-1);const m=String(Math.floor(breakLeft/60)).padStart(2,'0'),s=String(breakLeft%60).padStart(2,'0');$('#breakText').textContent=`${m}:${s}`;if(breakLeft===0){clearInterval(breakTimer);breakTimer=null;toast('休息结束，可以回到图谱了');$('#breakStart').textContent='开始休息'}},1000)};$('#drawBreak').onclick=drawBreakTip;$('#breakReset').onclick=()=>{if(breakTimer)clearInterval(breakTimer);breakTimer=null;breakLeft=state.settings.restMinutes*60;$('#breakText').textContent=String(state.settings.restMinutes).padStart(2,'0')+':00';$('#breakStart').textContent='开始休息'};
$('#generateReview').onclick=generateReview;$('#addTomorrowSuggestions').onclick=addTomorrowSuggestions;$('#celebrateMap').onclick=celebrate;
$('#saveSettings').onclick=()=>{state.settings.focusMinutes=Number($('#setFocus').value||45);state.settings.restMinutes=Number($('#setRest').value||10);state.settings.longRestMinutes=Number($('#setLongRest').value||20);state.settings.longRestEvery=Number($('#setLongEvery').value||4);breakLeft=state.settings.restMinutes*60;save();render();toast('已保存专注与休息设置')};$$('.quickMode').forEach(b=>b.onclick=()=>{$('#setFocus').value=b.dataset.f;$('#setRest').value=b.dataset.r;$('#saveSettings').click()});$('#saveApi').onclick=()=>{state.settings.apiParseUrl=$('#apiParseUrl').value.trim();state.settings.apiReviewUrl=$('#apiReviewUrl').value.trim();save();toast('已保存 API 设置')};$('#showApiGuide').onclick=()=>{const box=$('#apiGuide');box.style.display=box.style.display==='none'?'block':'none';box.textContent=apiGuideText()};$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='focusmap-data.json';a.click()};$('#loadDemo').onclick=()=>{state=demoState();save();setTheme(state.theme);go('home');toast('演示数据已载入')};$('#clearData').onclick=()=>{if(confirm('确定清空所有本地数据吗？')){state=defaultState();save();setTheme('space');go('home');toast('已清空')}};
breakLeft=state.settings.restMinutes*60;$('#breakText').textContent=String(state.settings.restMinutes).padStart(2,'0')+':00';render();}
wire();
